microsoft/automatic-graph-layout

README.md

Page: http://research.microsoft.com/en-us/projects/msagl/

Update README with MSR page details & images.

---

GraphLayout/MSAGL/Core/DataStructures/SymmetricTuple.cs
GraphLayout/MSAGL/Layout/LargeGraphLayout/LgData.cs
GraphLayout/MSAGL/Layout/LargeGraphLayout/LgInteractor.cs
GraphLayout/MSAGL/Layout/LargeGraphLayout/LgSkeletonLevel.cs
GraphLayout/MSAGL/Layout/LargeGraphLayout/NodeRailLevelCalculator/GreedyNodeRailLevelCalculator.cs
GraphLayout/MSAGL/Layout/OverlapRemovalFixedSegments/OverlapRemovalFixedSegmentsBitmap.cs
GraphLayout/MSAGL/Msagl.csproj
GraphLayout/MsaglSharpkit/MsaglSharpKit/MsaglSharpKit.csproj

Simplify some of the original MSAGL csproj to make keeping in sync
easier.
Add new files to MsaglSharpkit.
Add some conditional compilation to debug code.

Bring new files into MsaglSharpKit

---

GraphLayout/Test/MSAGLTests/Constraints/ProjectionSolverFileTests.cs

Fix #12 by increasing timeout by 1s. This doesn't time out all of the time, just some of the time. This change makes it so it doesn't timeout at all.

Fix #12 by increasing timeout by 1s.

---

GraphLayout/Drawing/NodeAttr.cs

sorry for the 2 commits, not sure how I could delete the first one that had a greek character in the comment so I added a 2nd commit to fix with english char the XML comment that I had added

Missing XML comment

---

GraphLayout/tools/GraphViewerGDI/GViewer.cs

https://github.com/Microsoft/automatic-graph-layout/issues/65

Resolve for issue #65

---

GraphLayout/NuGet/Microsoft.Msagl.Drawing.nuspec
GraphLayout/NuGet/Microsoft.Msagl.GraphViewerGDI.nuspec
GraphLayout/NuGet/Microsoft.Msagl.nuspec
GraphLayout/NuGet/build_nuget_packages.ps1

- package names are now standardized to Microsoft.Msagl
- added a third package NuGet for GraphViewerGDI

NuGet updates

---

GraphLayout/tools/WpfGraphControl/VNode.cs

Modify the setter to call the proper event

Add node selection for WPF viewer

---

GraphLayout/NuGet/Microsoft.Msagl.WpfGraphControl.nuspec
GraphLayout/NuGet/build_nuget_packages.ps1
GraphLayout/tools/WpfGraphControl/WpfGraphControl.csproj

Added Microsoft.Msagl.WpfGraphControl.nuspec file.
Changed build_nuget_packages.ps1 to include Microsoft.Msagl.WpfGraphControl.nuspec.
Enabled generation of XML Documentation in WpfGraphControl.csproj

Added Nuget Package for Microsoft.Msagl.WpfGraphControl.dll

---

GraphLayout/GraphLayout.NETCore.sln
GraphLayout/MSAGL.NETCore/MSAGL.NETCore.csproj
GraphLayout/MSAGL/Core/Layout/Edge.cs
GraphLayout/MSAGL/Core/Layout/LgNodeInfo.cs
GraphLayout/MSAGL/Core/Layout/ProximityOverlapRemoval/MST/GTreeOverlapRemoval.cs
GraphLayout/MSAGL/Core/Layout/ProximityOverlapRemoval/MST/MstOnDelaunayTriangulation.cs
GraphLayout/MSAGL/Core/Layout/ProximityOverlapRemoval/ProximityOverlapRemoval.cs
GraphLayout/MSAGL/Core/Layout/ProximityOverlapRemoval/StressEnergy/ExampleStressMajorization.cs
GraphLayout/MSAGL/Layout/LargeGraphLayout/LgData.cs
GraphLayout/MSAGL/Layout/LargeGraphLayout/LgInteractor.cs
GraphLayout/MSAGL/Layout/LargeGraphLayout/LgSkeletonLevel.cs
GraphLayout/MSAGL/Layout/LargeGraphLayout/NodeRailLevelCalculator/GreedyNodeRailLevelCalculator.cs
GraphLayout/MSAGL/Layout/LargeGraphLayout/Rail.cs
GraphLayout/MSAGL/Properties/AssemblyInfo.cs

Added initial support for .NET Standard 2.0

---

.gitignore
GraphLayout/NuGet/AcquireNuGetExe.ps1
GraphLayout/NuGet/build_nuget_packages.ps1
README.md

These updates make the process of getting the nuget.exe more reliable and more usable from the command line

NuGet packaging script updated

---

GraphLayout/NuGet/Microsoft.Msagl.Drawing.nuspec
GraphLayout/NuGet/Microsoft.Msagl.GraphViewerGDI.nuspec
GraphLayout/NuGet/Microsoft.Msagl.WpfGraphControl.nuspec
GraphLayout/NuGet/Microsoft.Msagl.nuspec
GraphLayout/NuGet/build_nuget_packages.ps1

updated the nuget version numbers

Updated nuget packages

---

GraphLayout/NuGet/Microsoft.Msagl.Drawing.nuspec
GraphLayout/NuGet/Microsoft.Msagl.GraphViewerGDI.nuspec
GraphLayout/NuGet/Microsoft.Msagl.WpfGraphControl.nuspec
GraphLayout/NuGet/Microsoft.Msagl.nuspec
GraphLayout/NuGet/build_nuget_packages.ps1

Update NuGet nuspecs to use Release instead of Debug

---

.editorconfig
GraphLayout/tools/GraphViewerGDI/GViewer.cs

- Added CustomOpenButtonPressed event
- Added .editorconfig

Added CustomOpenButtonPressed event

---

GraphLayout/MSAGL/Layout/LargeGraphLayout/LgData.cs

Some parts of the code were disabled in .NET Standard via conditional compilation. They build fine for me now and are needed with the present code.

Added some code for .NET Standard build

---

GraphLayout/MSAGL/Core/Layout/Cluster.cs
GraphLayout/MSAGL/Core/Layout/EdgeLabelPlacement.cs
GraphLayout/MSAGL/Routing/SplineRouter.cs

These are the fixes we found while debugging just now.

fix some bugs found while updating GraphViewer to the latest bits.

---

GraphLayout/MsaglSharpkit/WebMsagl/Scripts/src/ggraph.ts
GraphLayout/MsaglSharpkit/WebMsagl/Scripts/src/msagl.worker.ts

Exposing the IterationsWithMajorization MDS setting for use with JS.

MSAGL/JS: exposing IterationsWithMajorization.

---

GraphLayout/Drawing/NodeBoundaryCurves.cs
GraphLayout/MSAGL/Core/Geometry/Curves/CurveFactory.cs

Display Hexagon, and prevent the lines to overlap the content

Fix Hexagon

---

GraphLayout/MsaglSharpkit/WebMsagl/Scripts/src/msagl.worker.ts
GraphLayout/MsaglSharpkit/WebMsagl/Scripts/src/sharpkit_post.js

WebMsagl fixes

---

GraphLayout/Drawing/SvgGraphWriter.cs

#270 
- Fix SvgGraphWriter: export hexagon shape
- Fix SvgGraphWriter: export label as multi-line text

Fix issue #270

---

GraphLayout/GraphLayout.sln
GraphLayout/Samples/DrawingFromGeometryWithGtk/CommonDrawingUtilsForSamples.cs
GraphLayout/Samples/DrawingFromGeometryWithGtk/DrawingFromGeometryWithGtk.csproj
GraphLayout/Samples/DrawingFromGeometryWithGtk/MainWindow.cs
GraphLayout/Samples/DrawingFromGeometryWithGtk/MainWindow.glade
GraphLayout/Samples/DrawingFromGeometryWithGtk/Program.cs

Added a sample showcasing the use of MSAGL with GTK

Added Gtk Sample

---

GraphLayout/Samples/WpfApplicationSample/WpfApplicationSample.cs
GraphLayout/tools/WpfGraphControl/GraphViewer.cs
GraphLayout/tools/WpfGraphControl/VNode.cs

Implementation for #128, #276
Just enabled `TextBlock` creation for `Subgraph`. ~~Only at `Top` position for now (better than nothing).~~
Then fixed some overlapping issues

WPF Subgraph Label

---

GraphLayout/Drawing/LayoutEditing/GeometryGraphEditor.cs
GraphLayout/Samples/WpfApplicationSample/WpfApplicationSample.cs

Drag of Rectilinear Edges not affects Subgraph

---

README.md

Replace `Lg.sln` with `GraphLayout.sln`

There is no Lg.sln in the project
